Add `Prelude.Text.lowerASCII` utility
dhall-lang/dhall-lang pull request #1164
Opened 2021-05-04 01:12 UTC by Gabriel439

Related to https://github.com/dhall-lang/dhall-lang/issues/631

In particular, this is based on the suggestion from:

https://github.com/dhall-lang/dhall-lang/issues/631#issuecomment-831476805

2021-05-04 07:58 UTC, basile-henry commented on Prelude/Text/lowerASCII.dhall
> +      assert : "Á" ≡ "Á"
```suggestion
      assert : lowerASCII "Á" ≡ "Á"
```

2021-05-04 08:56 UTC, ad-si commented
Wouldn't it make sense to also include `upperASCII` while you're already at it?

2021-05-04 11:36 UTC, TristanCacqueray commented on Prelude/Text/lowerASCII.dhall
> +      assert : "Á" ≡ "Á"
The assertion might already be impressive, but it seems like what @basile-henry suggest is what we need here :-)

2021-05-04 20:32 UTC, MonoidMusician commented
You might want to add a warning that decomposed unicode characters (base character + modifier diacritics) may be affected by case conversion:
```dhall
assert : lowerASCII "Á" ≡ "á"
```
(I believe that is correct, but you should test!)

2021-05-07 09:16 UTC, ad-si requested changes

2021-05-07 09:16 UTC, ad-si commented on Prelude/Text/upperASCII.dhall
> +Note that this will also lowercase decomposed Unicode characters that contain
uppercase 😅

2021-05-07 09:16 UTC, ad-si commented on Prelude/Text/upperASCII.dhall
> +    -- • The `Á` in the following example is U+00C1
Should be `á`

2021-05-11 14:40 UTC, merged