Add `showConstructor` to convert union value constructor to `Text`
dhall-lang/dhall-lang pull request #1257
Opened 2021-12-31 20:24 UTC by darichey

Fixes #1204 

Adds a `showConstructor` keyword that can be used to convert a union value to `Text` by its constructor name. For example:

```dhall
⊢ :paste
-- Entering multi-line mode. Press <Ctrl-D> to finish.
| let Foo = < A | B : Natural | C : Natural -> Text >
| let a = showConstructor Foo.A
| let b = showConstructor (Foo.B 3)
| let c = showConstructor (Foo.C (\(n : Natural) -> ""))
| in
| "${a}${b}${c}"

"ABC"
```
It also works on `Optional` values:
```dhall
⊢ showConstructor (None Natural)

"None"

⊢ showConstructor (Some 0)

"Some"
```

2022-01-01 04:51 UTC, Gabriel439 reviewed
Looks great!  I think all this needs is tests

2022-01-01 04:51 UTC, Gabriel439 commented on standard/dhall.abnf
> +showConstructor      = %x73.68.6f.77.43.6f.6e.73.74.72.75.63.74.6f.72
```suggestion
showConstructor       = %x73.68.6f.77.43.6f.6e.73.74.72.75.63.74.6f.72

```

2022-01-01 04:51 UTC, Gabriel439 commented on standard/type-inference.md
> +If the first argument of a `showConstructor` expression is not a union or an
It's also worth noting that if the first argument of `showConstructor` is an empty union then that's also a type error.  This can happen for an expression like this:

```dhall
λ(a : <>) → showConstructor a
```

2022-01-01 06:20 UTC, MonoidMusician commented on standard/type-inference.md
> +If the first argument of a `showConstructor` expression is not a union or an
An empty union should be fine, it just means it’s the absurd function `<> -> Text`.

But I see what’s happening now: the check is overly restrictive. Typechecking shouldn’t need to see the value of the argument, only its type. As currently written, it is basically a macro that requires a statically known argument, not a function that can take any argument of the specified type.

2022-01-01 06:53 UTC, MonoidMusician commented on standard/type-inference.md
> +If the first argument of a `showConstructor` expression is not a union or an
(It looks like the draft implementation already has it done the way I was suggesting.)

2022-01-01 17:12 UTC, Gabriel439 commented on standard/type-inference.md
> +If the first argument of a `showConstructor` expression is not a union or an
Oh, whoops, you're right.  Ignore my comment, then ☺️

2022-01-01 23:12 UTC, MonoidMusician requested changes
Looks good to me, just this one detail.

2022-01-01 23:12 UTC, MonoidMusician commented on standard/type-inference.md
> +    Γ ⊢ showConstructor u.x : Text
Following up from my other comment, I would recommend this rule so that it works for abstract expressions too, in line with your draft implementation:

```suggestion
    Γ ⊢ e : < ts… >
    ──────────────────────────────
    Γ ⊢ showConstructor e : Text
```

2022-01-02 00:11 UTC, darichey commented on standard/type-inference.md
> +    Γ ⊢ showConstructor u.x : Text
Makes sense! Thanks!

2022-01-02 01:20 UTC, MonoidMusician approved these changes

2022-01-02 03:45 UTC, Gabriel439 approved these changes

2022-01-02 21:37 UTC, sjakobi reviewed
Looks like a great feature! :)

I've been trying to think of some "interesting" type-inference failure tests. So far I've only come up with:

* `showConstructor < A : Bool >.A`
* `showConstructor None`

Please also add type-inference and normalization success tests for something like `showConstructor (< A : Bool>.A False)`.

I also wonder whether `showConstructor` ought to work for `Bool`s. I don't see why not. Our [main reason](https://github.com/dhall-lang/dhall-lang/issues/463#issuecomment-563341537) for not allowing `merge` for `Bool`s doesn't seem to apply in this case.

2022-01-02 22:09 UTC, darichey commented
Thanks for the test suggestions! I've added those.

`showConstructor` for `Bool`s sounds reasonable, though I wonder what the use case would be where you wouldn't just use `Bool/show`.

2022-01-02 22:18 UTC, sjakobi reviewed
> showConstructor for Bools sounds reasonable, though I wonder what the use case would be where you wouldn't just use Bool/show.

It might be just slightly more convenient than importing `Bool/show` from the Prelude. Not a very important addition though.

2022-01-02 22:18 UTC, sjakobi commented on tests/type-inference/success/unit/ShowConstructorNonEmptyB.dhall
> +"A"
```suggestion
Text
```

2022-01-02 22:18 UTC, sjakobi commented on tests/type-inference/success/unit/ShowConstructorEmptyB.dhall
> +"A"
```suggestion
Text
```

2022-01-02 22:18 UTC, sjakobi commented on tests/normalization/success/unit/ShowConstructorNonEmptyB.dhall
> +Text
```suggestion
"A"
```

2022-01-02 22:18 UTC, sjakobi commented on tests/normalization/success/unit/ShowConstructorEmptyB.dhall
> +Text
```suggestion
"A"
```

2022-01-02 22:20 UTC, darichey commented on tests/normalization/success/unit/ShowConstructorEmptyB.dhall
> +Text
Whoops :sweat_smile:

2022-01-04 00:27 UTC, sjakobi approved these changes

2022-01-07 16:42 UTC, merged